<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * German translation for the MailWizz category "users" (du form).
 * Source: https://github.com/brightcolor/mailwizz-deutsch
 */
return array (
  'Remember me' => 'Angemeldet bleiben',
  '2FA code' => '2FA-Code',
  'Invalid login credentials.' => 'Die Zugangsdaten stimmen nicht. Prüfe E-Mail-Adresse und Passwort.',
  'Unable to login with the given identity!' => 'Die Anmeldung mit diesen Daten ist fehlgeschlagen. Prüfe deine Angaben und versuche es erneut.',
  'View users' => 'Benutzer ansehen',
  'Users' => 'Benutzer',
  'Create new user' => 'Neuen Benutzer anlegen',
  'You are not allowed to update the master administrator!' => 'Den Hauptadministrator darfst du nicht bearbeiten.',
  'Update user' => 'Benutzer bearbeiten',
  'Update account' => 'Konto bearbeiten',
  'User info successfully updated!' => 'Die Benutzerdaten sind gespeichert.',
  '2FA' => '2FA',
  'Please login' => 'Bitte melde dich an',
  'Retrieve a new password for your account.' => 'Lass dir ein neues Passwort für dein Konto schicken.',
  'Update user group' => 'Benutzergruppe bearbeiten',
  'Use any authenticator app such as Google Authenticator to scan the QR code below.' => 'Scanne den QR-Code unten mit einer Authenticator-App, etwa Google Authenticator.',
  'You will then use the authenticator app to generate the code to login in the app.' => 'Den Code für die Anmeldung erzeugst du dann mit der Authenticator-App.',
  'Sign in to start your session' => 'Melde dich an, um loszulegen',
  'Forgot password?' => 'Passwort vergessen?',
  'Go to login' => 'Zur Anmeldung',
  'Enter the code generated by the authenticator app' => 'Gib den Code aus deiner Authenticator-App ein',
  'Update your account data.' => 'Bearbeite deine Kontodaten.',
  'User' => 'Benutzer',
  'Language' => 'Sprache',
  'Group' => 'Gruppe',
  'First name' => 'Vorname',
  'Last name' => 'Nachname',
  'Email' => 'E-Mail',
  'Password' => 'Passwort',
  'Timezone' => 'Zeitzone',
  'Avatar' => 'Profilbild',
  'New avatar' => 'Neues Profilbild',
  'Removable' => 'Entfernbar',
  'Confirm email' => 'E-Mail-Adresse bestätigen',
  'Confirm password' => 'Passwort bestätigen',
  '2FA enabled' => '2FA aktiviert',
  'Please make sure you scan the QR code in your authenticator application before enabling this feature, otherwise you will be locked out from your account' => 'Scanne den QR-Code unbedingt mit deiner Authenticator-App, bevor du diese Funktion einschaltest. Sonst sperrst du dich aus deinem Konto aus.',
  'The avatars storage directory({path}) does not exists and cannot be created!' => 'Das Verzeichnis für Profilbilder ({path}) fehlt und ließ sich nicht anlegen.',
  'Cannot move the avatar into the correct storage folder!' => 'Das Profilbild ließ sich nicht in den richtigen Ordner verschieben.',
  'Request' => 'Anfrage',
  'Reset key' => 'Schlüssel zum Zurücksetzen',
  'Ip address' => 'IP-Adresse',
  'Token' => 'Token',
  'You are impersonating the customer {customerName}.' => 'Du bist als Kunde {customerName} angemeldet.',
  'Please click {linkBack} to logout in order to finish impersonating.' => 'Klick auf {linkBack}, um dich abzumelden und die Anmeldung als Kunde zu beenden.',
);
