<?php
// German texts for the MailWizz table "common_email_template".
// mode "whole": the field is replaced when its whole value equals the English text.
// mode "fragment": every occurrence of the English piece inside the field is replaced.
// Whitespace differences are ignored when matching. Tags must stay the same.

return array (
  'table' => 'common_email_template',
  'rules' => 
  array (
    0 => 
    array (
      'field' => 'name',
      'mode' => 'whole',
      'pairs' => 
      array (
        'Delivery server validation' => 'Bestätigung eines Versandservers',
        'Campaign pending approval' => 'Kampagne wartet auf Freigabe',
        'Campaign pending approval - approved' => 'Kampagnenfreigabe – freigegeben',
        'Campaign pending approval - disapproved' => 'Kampagnenfreigabe – abgelehnt',
        'Campaign has been blocked' => 'Kampagne blockiert',
        'Campaign stats' => 'Kampagnenstatistik',
        'Campaign share reports access' => 'Zugang zu freigegebenen Kampagnenberichten',
        'Customer confirm registration' => 'Kunde bestätigt Registrierung',
        'New customer registration' => 'Neue Kundenregistrierung',
        'New list subscriber' => 'Neuer Abonnent einer Liste',
        'Email blacklist import finished' => 'Import in die Sperrliste abgeschlossen',
        'Auto update notification' => 'Benachrichtigung zur automatischen Aktualisierung',
        'Email blacklist monitor results' => 'Ergebnisse des Sperrlisten-Monitors',
        'Suppression list import finished' => 'Import in die Ausschlussliste abgeschlossen',
        'Order invoice' => 'Rechnung zur Bestellung',
        'List import finished' => 'Import in eine Liste abgeschlossen',
        'Password reset request' => 'Anfrage zum Zurücksetzen des Passworts',
        'New login info' => 'Neue Zugangsdaten',
        'New order placed - user' => 'Neue Bestellung – Admin',
        'New order placed - customer' => 'Neue Bestellung – Kunde',
        'Account approved' => 'Konto freigegeben',
        'Account details' => 'Kontodaten',
        'List subscriber unsubscribed' => 'Abonnent hat sich abgemeldet',
        'Confirm block email request' => 'Anfrage zum Sperren einer E-Mail-Adresse bestätigen',
        'Forward campaign to a friend' => 'Kampagne an Freunde weiterleiten',
        'New abuse report' => 'Neue Missbrauchsmeldung',
        'Scheduled inactive customers' => 'Als inaktiv markierte Kunden',
        'Sending domain DNS records' => 'DNS-Einträge einer Absenderdomain',
      ),
    ),
    1 => 
    array (
      'field' => 'subject',
      'mode' => 'whole',
      'pairs' => 
      array (
        'Please validate this server.' => 'Bitte bestätige diesen Server.',
        'A campaign requires approval before sending!' => 'Eine Kampagne muss vor dem Versand freigegeben werden',
        'Your campaign has been approved!' => 'Deine Kampagne ist freigegeben',
        'Your campaign has been disapproved!' => 'Deine Kampagne wurde abgelehnt',
        'A campaign has been blocked!' => 'Eine Kampagne wurde blockiert',
        'The campaign [CAMPAIGN_NAME] has finished sending, here are the stats' => 'Die Kampagne [CAMPAIGN_NAME] ist versendet, hier ist die Statistik',
        'Campaign share reports access!' => 'Zugang zu den Berichten einer Kampagne',
        'Please confirm your account!' => 'Bitte bestätige dein Konto',
        'New customer registration!' => 'Neue Kundenregistrierung',
        'New list subscriber!' => 'Neuer Abonnent in deiner Liste',
        'Email blacklist import has finished!' => 'Der Import in die Sperrliste ist abgeschlossen',
        'Automatic update notification!' => 'Automatische Aktualisierung',
        'Blacklist monitor results for: [MONITOR_NAME]' => 'Ergebnisse des Sperrlisten-Monitors: [MONITOR_NAME]',
        'Suppression list import has finished!' => 'Der Import in die Ausschlussliste ist abgeschlossen',
        'Your requested invoice - [REF]!' => 'Deine angeforderte Rechnung – [REF]',
        'List import has finished!' => 'Der Import in deine Liste ist abgeschlossen',
        'Password reset request!' => 'Passwort zurücksetzen',
        'Your new login info!' => 'Deine neuen Zugangsdaten',
        'A new order has been placed!' => 'Eine neue Bestellung ist eingegangen',
        'Your order details!' => 'Die Details deiner Bestellung',
        'Your account has been approved!' => 'Dein Konto ist freigegeben',
        'Your account details!' => 'Deine Kontodaten',
        'List subscriber unsubscribed!' => 'Ein Abonnent hat sich abgemeldet',
        'Confirm the block email request!' => 'Bitte bestätige die Anfrage zum Sperren deiner E-Mail-Adresse',
        'Your friend [FROM_NAME] thought you might like this!' => '[FROM_NAME] meint, das könnte dir gefallen',
        'New abuse report!' => 'Neue Missbrauchsmeldung',
        'Scheduled inactive customers' => 'Als inaktiv markierte Kunden',
        'Please add the following DNS records to the [DOMAIN_NAME] domain' => 'Bitte lege diese DNS-Einträge für die Domain [DOMAIN_NAME] an',
      ),
    ),
    2 => 
    array (
      'field' => 'content',
      'mode' => 'fragment',
      'pairs' => 
      array (
        'Your confirmation key for the server "<em>[HOSTNAME]</em>" is:' => 'Dein Bestätigungsschlüssel für den Server „<em>[HOSTNAME]</em>“ lautet:',
        'If for some reason the above link does not work, please type the following url in your browser address bar:' => 'Falls der Link oben nicht funktioniert, gib diese Adresse in die Adresszeile deines Browsers ein:',
        'A campaign requires approval before sending!' => 'Eine Kampagne muss vor dem Versand freigegeben werden.',
        'Click here to see it and take action!' => 'Hier klicken, um sie anzusehen und zu entscheiden.',
        'Your campaign has been approved for sending and will start as scheduled.' => 'Deine Kampagne ist für den Versand freigegeben und startet wie geplant.',
        'Click here to see the campaign details.' => 'Hier klicken, um die Details der Kampagne zu sehen.',
        'Your campaign has been disapproved with the following message:' => 'Deine Kampagne wurde mit dieser Nachricht abgelehnt:',
        'Click here to update your campaign and submit it again.' => 'Hier klicken, um deine Kampagne zu bearbeiten und erneut einzureichen.',
        'A campaign sending has been blocked because of the following reasons:' => 'Der Versand einer Kampagne wurde aus diesen Gründen blockiert:',
        'You have been invited to view reports for the campaign "[CAMPAIGN_NAME]".' => 'Du bist eingeladen, die Berichte der Kampagne „[CAMPAIGN_NAME]“ anzusehen.',
        'Please follow the following url in order to confirm your registration:' => 'Bitte öffne diese Adresse, um deine Registrierung zu bestätigen:',
        'If for some reason you cannot click the above url, please paste this one into your browser address bar:' => 'Falls sich die Adresse oben nicht anklicken lässt, kopiere sie in die Adresszeile deines Browsers:',
        'A new customer registration has been made as follows:' => 'Ein neuer Kunde hat sich registriert:',
        'The customer details url is as follows:' => 'Die Details des Kunden findest du hier:',
        'A new subscriber has been added to your list.' => 'In deiner Liste wurde ein neuer Abonnent eingetragen.',
        'Details url:' => 'Details:',
        'Submitted data:' => 'Übermittelte Daten:',
        'This is a notification to let you know that the import process for the email blacklist has finished!' => 'Der Import in die Sperrliste ist abgeschlossen.',
        'The imported file is "[FILE_NAME]"' => 'Importiert wurde die Datei „[FILE_NAME]“',
        'Click <a href="[OVERVIEW_URL]">here</a> to see the overview page!' => 'Zur Übersicht geht es <a href="[OVERVIEW_URL]">hier</a>.',
        'The monitor [MONITOR_NAME] finished processing [COUNT] records, [SUCCESS_COUNT] with success and [ERROR_COUNT] with error!' => 'Der Monitor [MONITOR_NAME] hat [COUNT] Einträge verarbeitet: [SUCCESS_COUNT] erfolgreich, [ERROR_COUNT] mit Fehler.',
        'This is a notification to let you know that the import process for the list "[LIST_NAME]" has finished!' => 'Der Import in die Liste „[LIST_NAME]“ ist abgeschlossen.',
        'Click <a href="[OVERVIEW_URL]">here</a> to see the list overview page!' => 'Zur Übersicht der Liste geht es <a href="[OVERVIEW_URL]">hier</a>.',
        'As requested, attached is your order invoice with reference number: [REF]' => 'Wie gewünscht findest du im Anhang die Rechnung zu deiner Bestellung mit der Nummer [REF]',
        'If you have any questions regarding this invoice, please contact us.' => 'Hast du Fragen zu dieser Rechnung, melde dich gern bei uns.',
        'Please follow the following url in order to reset your password:' => 'Bitte öffne diese Adresse, um dein Passwort zurückzusetzen:',
        'Your new login is:' => 'Deine neuen Zugangsdaten:',
        'You can login by clicking <a href="[LOGIN_URL]">here</a>' => 'Anmelden kannst du dich <a href="[LOGIN_URL]">hier</a>',
        'If for some reason the link doesn\'t work, please copy the following url into your browser address bar:' => 'Falls der Link nicht funktioniert, kopiere diese Adresse in die Adresszeile deines Browsers:',
        'A new order has been placed on your [SITE_NAME] website as follows:' => 'Auf deiner Website [SITE_NAME] ist diese neue Bestellung eingegangen:',
        'Your new order has been placed on [SITE_NAME] website as follows:' => 'Deine neue Bestellung auf [SITE_NAME]:',
        '>Customer</th>' => '>Kunde</th>',
        '>Price plan</th>' => '>Tarif</th>',
        '>Subtotal:</th>' => '>Zwischensumme:</th>',
        '>Tax:</th>' => '>Steuer:</th>',
        '>Discount:</th>' => '>Rabatt:</th>',
        '>Total:</th>' => '>Gesamt:</th>',
        'You can view the full order if you login into the application at:' => 'Die vollständige Bestellung siehst du nach der Anmeldung unter:',
        'Congratulations, your account on [SITE_NAME] has been approved and you can now login using the url below:' => 'Glückwunsch, dein Konto auf [SITE_NAME] ist freigegeben. Du kannst dich jetzt über diese Adresse anmelden:',
        'Your account details on [SITE_NAME] changed as follow:' => 'Deine Zugangsdaten auf [SITE_NAME] haben sich geändert:',
        'A subscriber has been unsubscribed from your list.' => 'Ein Abonnent hat sich von deiner Liste abgemeldet.',
        'Subscriber email:' => 'E-Mail-Adresse des Abonnenten:',
        'Please click the link below in order to confirm the block email request.' => 'Bitte klick auf den Link unten, um die Anfrage zum Sperren deiner E-Mail-Adresse zu bestätigen.',
        'If for some reason the link is not clickable, please copy and paste it in your browser address bar!' => 'Falls sich der Link nicht anklicken lässt, kopiere ihn in die Adresszeile deines Browsers.',
        '[FROM_NAME] thought you might like the following url:' => '[FROM_NAME] meint, dieser Link könnte dir gefallen:',
        'A new abuse report has been created for the campaign "[CAMPAIGN_NAME]".' => 'Zur Kampagne „[CAMPAIGN_NAME]“ gibt es eine neue Missbrauchsmeldung.',
        'Please visit the "<a href="[ABUSE_REPORTS_URL]">Abuse Reports</a>" area to handle it!' => 'Bearbeite sie im Bereich „<a href="[ABUSE_REPORTS_URL]">Missbrauchsmeldungen</a>“.',
        'The following customers were marked as inactive as per your settings:' => 'Diese Kunden wurden gemäß deinen Einstellungen als inaktiv markiert:',
        'Please edit your DNS records for <em>[DOMAIN_NAME]</em> domain and add the following TXT record:' => 'Bitte ergänze die DNS-Einträge der Domain <em>[DOMAIN_NAME]</em> um diesen TXT-Eintrag:',
        'For best delivery rates, your domain SPF record must look like:' => 'Für die beste Zustellung sollte der SPF-Eintrag deiner Domain so aussehen:',
        'For best delivery rates, your domain DMARC record must look like:' => 'Für die beste Zustellung sollte der DMARC-Eintrag deiner Domain so aussehen:',
        'Hello [CUSTOMER_NAME],' => 'Hallo [CUSTOMER_NAME],',
        'Hello [CUSTOMER_NAME]' => 'Hallo [CUSTOMER_NAME]',
        'Hello [USER_NAME],' => 'Hallo [USER_NAME],',
        'Hello [USER_NAME]' => 'Hallo [USER_NAME]',
        'Hello [TO_NAME],' => 'Hallo [TO_NAME],',
        'Hello,' => 'Hallo,',
        'List name:' => 'Liste:',
        'Password:' => 'Passwort:',
        'Email:' => 'E-Mail:',
        'Url:' => 'Adresse:',
        'All rights reserved' => 'Alle Rechte vorbehalten',
      ),
    ),
  ),
);
